title: Sandra Vidal
logo: pic2.jpg
description: Apasionada por transformar datos en decisiones claras. Egresada de TripleTen, con proyectos reales en análisis de usuarios, visualización y predicción de comportamientos.
theme: jekyll-theme-minimal
