title: Sandra Vidal
logo: <img src="pic2.jpg" alt="Foto de Sandra" style="width:200px; border-radius:50%;">
description: Apasionada por transformar datos en decisiones claras. Egresada de TripleTen, con proyectos reales en análisis de usuarios, visualización y predicción de comportamientos.
#show_downloads: true
theme: jekyll-theme-minimal
