title: Sandra Vidal
logo: <img src="pic2.jpg" alt="Foto de Sandra" style="width:200px; border-radius:50%;">
description: Analista de Datos Jr. con formación en Python, SQL y Tableu.
#show_downloads: true
theme: jekyll-theme-minimal
