title: Sandra Vidal
Logo: <p align="center"> <img src="https://drive.google.com/file/d/1XmuhQBoPpYqjHN6FZta2sigh6JvELJNc/view?usp=drive_link" alt="banner" height="300" /> 
descripcion: Analista de Datos Jr. con formación en Python, SQL y Tableu.
#show_downloads: true
theme: jekyll-theme-minimal
