title: Sandra Vidal
Logo: https://github.com/meli6432/meli6432.github.io/blob/21887eac0058c311bc3344dd9ec60c4b897ebd7e/pic2.jpg
descripcion: Analista de Datos Jr. con formación en Python, SQL y Tableu.
#show_downloads: true
theme: jekyll-theme-minimal
