title: Sandra Vidal
Logo: https://drive.google.com/drive/home
descripcion: Analista de Datos Jr. con formaci칩n en Python, SQL y Tableu.
Apasionada por transformar datos en decisiones claras. Egresada de TripleTen, con proyectos reales en an치lisis de usuarios, visualizaci칩n y predicci칩n de comportamientos.
#show_downloads: true
theme: jekyll-theme-minimal
